AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'build/**/*'
    - 'coverage/**/*'
    - 'spec/fixtures/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
