#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'veltrunode'
require 'veltrunode/cli'

begin
  Veltrunode::CLI.start(ARGV)
rescue Veltrunode::Error => e
  warn "Error: #{e.message}"
  exit 1
end
