name: Release Drafter

on:
  push:
    branches:
      - main
  # Also run on pull_request to update/verify release drafts or show what the next version would be
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required for release-drafter to create/update releases/tags
      contents: write
      # write permission is required for release-drafter to write comments/labels to PRs
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-config.yml
          publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
